export const CLIENT_ID = 'NDL4SVTZB2XELT4MHNMS5TMSTHRPGA123AD4J0AB0GMM3QQS';
export const CLIENT_SECRET = 'BCAHGCPLUPHD2TLZXI1MX3LTFJ3EKWJJSAL4UUM4AORT50DQ';

export const environment = {
    production: true
  };
  